version: 2

project_name: ags

release:
  github:
    owner: nishantdesai
    name: coding-agent-account-switcher

before:
  hooks:
    - go mod tidy

builds:
  - id: ags
    main: ./cmd/ags
    binary: ags
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/nishantdesai/coding-agent-account-switcher/internal/ags.Version={{.Version}}

archives:
  - id: default
    ids:
      - ags
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

brews:
  - name: ags
    ids:
      - default
    homepage: https://github.com/nishantdesai/coding-agent-account-switcher
    description: CLI for saving and switching codex and pi auth profiles
    license: MIT
    directory: Formula
    repository:
      owner: nishantdesai
      name: homebrew-ags
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: github-actions[bot]
      email: [email protected]
    commit_msg_template: "brew: update ags to {{ .Tag }}"
    install: |
      bin.install "ags"
    test: |
      assert_match "ags version", shell_output("#{bin}/ags version")

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
