version: 2

project_name: ags

release:
  github:
    owner: nishantdesai
    name: coding-agent-account-switcher

before:
  hooks:
    - go mod tidy

builds:
  - id: ags
    main: ./cmd/ags
    binary: ags
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/nishantdesai/coding-agent-account-switcher/internal/ags.Version={{.Version}}

archives:
  - id: default
    ids:
      - ags
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
